// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Prisma CLI commands (unlike `next dev`) only read plain `.env` by
// default — plain `dotenv/config` doesn't know about Next.js's
// `.env.local` convention. Loading both here, in this order, restores
// the precedence `next dev` already uses: dotenv's config() never
// overwrites a variable already present in process.env, so loading
// `.env.local` FIRST means it wins over `.env` (loaded second, as the
// fallback for anything still unset) — and a variable set on the shell
// immediately before the command (e.g. `MIGRATE_DATABASE_URL=... npx
// prisma ...`) wins over both, since it's already in process.env before
// either load runs. `.env.local` is never committed or present in any
// deployed environment, so none of this affects `migrate deploy` in
// CI/production.
dotenv.config({ path: ".env.local" });
dotenv.config({ path: ".env" });

const resolvedUrl = process.env["MIGRATE_DATABASE_URL"] ?? process.env["DATABASE_URL"];

// Belt-and-suspenders on top of the .env.local load above: `prisma
// migrate dev` is documented by Prisma itself as a local-only command —
// it can reset/drop a database without the safeguards `migrate deploy`
// has, and should never run against a shared database, regardless of
// why the URL above resolved the way it did (missing .env.local, a
// stale shell export, a different machine). Scoped to `migrate dev`
// specifically by checking argv, since Prisma's config API doesn't hand
// the subcommand to datasource.url directly — `migrate deploy`,
// `generate`, `studio` etc. are all unaffected.
const isMigrateDev = process.argv.includes("migrate") && process.argv.includes("dev");
const looksLocal = (url: string) => /localhost|127\.0\.0\.1|::1/.test(url);
if (isMigrateDev && resolvedUrl && !looksLocal(resolvedUrl)) {
  throw new Error(
    "Refusing to run `prisma migrate dev` — the resolved database URL doesn't look local " +
      "(no localhost/127.0.0.1/::1 in it). `migrate dev` is local development only; use " +
      "`migrate deploy` for a shared database. If this is genuinely intentional, override " +
      "MIGRATE_DATABASE_URL explicitly for this one command."
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations need CREATE/role-management privileges the restricted
    // runtime role doesn't have — see .env.example.
    url: resolvedUrl,
  },
});
