import type { Metadata } from "next";
import { LegalPage } from "@/components/site/legal-page";
import { SITE_URL, SITE_HOST } from "@/lib/site-url";

const PAGE_TITLE = "Privacy Policy | Lavelle Institute";
const PAGE_DESCRIPTION =
  "How Lavelle Institute collects, uses, and protects your personal information across our website, candidate portal, and credential verification service.";

export const metadata: Metadata = {
  title: PAGE_TITLE,
  description: PAGE_DESCRIPTION,
  alternates: { canonical: `${SITE_URL}/privacy` },
  openGraph: {
    title: PAGE_TITLE,
    description: PAGE_DESCRIPTION,
    url: `${SITE_URL}/privacy`,
    siteName: "Lavelle Institute",
    type: "website",
  },
  twitter: { card: "summary_large_image" },
};

export default function PrivacyPolicyPage() {
  return (
    <LegalPage title="Privacy Policy" lastUpdated="10 September 2026">
      <p>
        Lavelle Institute (&ldquo;Lavelle&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) provides professional legal
        specialization and continuing professional development programmes for the Nigerian legal market, including
        an online candidate portal, a document template library, and a public credential verification service. This
        policy explains what personal information we collect, why we collect it, and the choices you have. It
        applies to {SITE_HOST} and every subdomain and related service we operate.
      </p>

      <h2>1. Information we collect</h2>
      <p>We collect information you give us directly, information generated by your use of our services, and information collected automatically.</p>

      <h3>Account and registration information</h3>
      <ul>
        <li>Full name, email address, phone number, and password</li>
        <li>Professional status (e.g. practising lawyer, law student), years of experience, and related qualifying details</li>
        <li>A unique applicant and, on enrolment, candidate number issued by us</li>
        <li>Programme, cohort, and intake selections; assessment and examination results</li>
      </ul>

      <h3>Payment information</h3>
      <p>
        Fees for programmes and library templates are processed by a third-party payment provider. We do not store
        your full card, bank, or transfer credentials — we retain only transaction references, amounts, and status
        needed to reconcile your account.
      </p>

      <h3>Content you submit</h3>
      <p>
        Messages sent through our contact form, support emails, and any documents or information you provide during
        enrolment, assessment, or verification requests.
      </p>

      <h3>Usage and device information</h3>
      <p>
        Pages visited, actions taken in the candidate portal, browser and device type, IP address, and
        referring/exit pages, collected through cookies and similar technologies described in Section 5.
      </p>

      <h2>2. How we use your information</h2>
      <ul>
        <li>To create and administer your candidate account and process enrolments</li>
        <li>To deliver programme content, schedule examinations, and record results</li>
        <li>To process payments and issue receipts</li>
        <li>To issue credentials and operate the public verification service at /verify</li>
        <li>To respond to enquiries sent via our contact form or support email addresses</li>
        <li>To send service communications (enrolment confirmations, results, password resets) and, where you have opted in, programme updates</li>
        <li>To maintain the security and integrity of our platform, including detecting fraud and abuse</li>
        <li>To comply with legal and regulatory obligations</li>
      </ul>

      <h2>3. Legal basis for processing</h2>
      <p>
        Where the Nigeria Data Protection Act 2023 and its regulations apply, we process your personal data on the
        basis of: performance of a contract (delivering the programme you enrolled in), your consent (e.g. marketing
        communications and non-essential cookies), our legitimate interests (platform security, service
        improvement), and compliance with legal obligations.
      </p>

      <h2>4. Credential verification and public information</h2>
      <p>
        Where you are issued a Lavelle credential, your name, candidate number, programme, and credential status
        become visible to anyone who looks them up through our public verification tool, so that employers and
        third parties can confirm the credential is genuine. We do not publish your contact details, payment
        history, or assessment scores through this tool. You can contact registrar@lavelle.ng with questions about
        what is shown for your record.
      </p>

      <h2>5. Cookies and similar technologies</h2>
      <p>We use cookies and similar technologies to:</p>
      <ul>
        <li>Keep you signed in and remember your session (strictly necessary — cannot be disabled without breaking core functionality)</li>
        <li>Understand how our site is used so we can improve it (analytics)</li>
      </ul>
      <p>
        You can control non-essential cookies through the cookie banner shown on your first visit, or at any time
        through your browser settings. Disabling strictly necessary cookies will prevent you from signing in or
        completing a purchase.
      </p>

      <h2>6. How we share your information</h2>
      <p>We do not sell your personal information. We share it only with:</p>
      <ul>
        <li>Payment processors, to complete and reconcile transactions</li>
        <li>Hosting, database, and email delivery providers who process data on our behalf under contract</li>
        <li>Faculty and examiners, limited to what is needed to deliver and assess your programme</li>
        <li>Employers or other third parties, but only the limited credential-status information described in Section 4, and only when they look up a credential themselves</li>
        <li>Regulators, courts, or authorities where we are legally required to do so</li>
      </ul>

      <h2>7. Data retention</h2>
      <p>
        We retain candidate and credential records for as long as needed to administer your enrolment, support
        ongoing credential verification, and meet our regulatory and record-keeping obligations. Marketing
        preferences and non-essential cookies are retained only until you withdraw consent or they expire.
      </p>

      <h2>8. Your rights</h2>
      <p>Subject to applicable law, you may:</p>
      <ul>
        <li>Request a copy of the personal information we hold about you</li>
        <li>Ask us to correct inaccurate or incomplete information</li>
        <li>Ask us to delete your information, except where we are required to retain it (e.g. to preserve the integrity of an issued credential)</li>
        <li>Object to or restrict certain processing, including marketing communications</li>
        <li>Withdraw consent at any time where processing is based on consent</li>
      </ul>
      <p>To exercise any of these rights, contact us at candidates@lavelle.ng.</p>

      <h2>9. Data security</h2>
      <p>
        We use administrative, technical, and physical safeguards designed to protect your information, including
        encrypted transmission, access controls, and password hashing. No method of transmission or storage is
        completely secure, and we cannot guarantee absolute security.
      </p>

      <h2>10. Children&rsquo;s privacy</h2>
      <p>Our services are intended for legal professionals, graduates, and students and are not directed at children under 18.</p>

      <h2>11. International data transfers</h2>
      <p>
        Our infrastructure providers may process data outside Nigeria. Where this occurs, we take steps to ensure
        an appropriate level of protection consistent with applicable data protection law.
      </p>

      <h2>12. Changes to this policy</h2>
      <p>
        We may update this policy from time to time. The &ldquo;Last updated&rdquo; date at the top reflects the
        most recent revision. Material changes will be communicated to registered candidates by email or through
        the portal.
      </p>

      <h2>13. Contact us</h2>
      <p>
        Questions about this policy or how we handle your information can be sent to{" "}
        <a href="mailto:candidates@lavelle.ng">candidates@lavelle.ng</a>. Lavelle Institute, Lagos, Nigeria.
      </p>
    </LegalPage>
  );
}
